### ISSUE TITLE
Middleware registration

### ISSUE THREAD

**Issue by devope** [alkhatibdev/language-switcher#3]
I guess it is worth mentioning in README.md that user should register middleware in `app/Http/Kernel.php`

```php
class Kernel extends HttpKernel
{
    // ...

    protected $middlewareGroups = [
        'web' => [
            // ...
            AlkhatibDev\LanguageSwitcher\Http\Middleware\SwitchLocale::class,
        ],
}
```

**Comment by alkhatibdev** [comment]
Hi @devope,

This actually mentioned at Readme under this section [(Assign to middleware groups)](https://github.com/alkhatibdev/language-switcher?tab=readme-ov-file#assign-to-middleware-groups)

The example uses the alias `switchlocale` over the class name for simplicity

Thanks, And I appreciate your feedback.

**Comment by devope** [comment]
Isn't it under `## Customize Package Scope`?

You say there:
> By default, the package middleware is assigned globally to all your routes.

For me it sounds like if I will not "customize" something somewhere it will work just fine.
Correct me if I am missing something.
Thanks!

**Comment by alkhatibdev** [comment]
> You say there:
> 
> > By default, the package middleware is assigned globally to all your routes.
> 
> For me it sounds like if I will not "customize" something somewhere it will work just fine. Correct me if I am missing something. Thanks!

Yes, that’s correct!

By default, the `assign_globally` flag in the configuration is set to `true`, ensuring the middleware is automatically applied to all routes without requiring additional setup. This approach simplifies the initial implementation for developers. However, the package remains fully customizable, allowing developers to adjust the behavior based on their specific needs.
